# ansible-playbook -i ~/ansible/hosts /playbooks/new-default.yml
---
- hosts: defaultdevices
  gather_facts: yes
  vars:
    wifi_country: "US"
    locale: "en_US.UTF-8"
    keyboard: "pc104"
    keyboard_layout: "us"
    virtualenvwrapper_source: "/usr/local/bin/virtualenvwrapper.sh"
    virtualenvwrapper_home: "{{ lookup('env', 'HOME') }}/.virtualenvs/"
    virtualenvwrapper_shell_file: "{{ lookup('env', 'HOME') }}/.bashrc"
    timezone: America/New_York
    locale_options:
      # Disable Default (GB) Locale
      - regexp: "^#?en_GB.UTF-8 UTF-8"
        line: "# en_GB.UTF-8 UTF-8"
      # Enable US Locale
      - regexp: "^#?en_US.UTF-8 UTF-8"
        line: "en_US.UTF-8 UTF-8"

  vars_prompt:

  - name: hostname
    prompt: "please enter a hostname for your new device:"
    private: no
  # - name: wifi_ssid
  #   prompt: "please enter the WiFi SSID for your new device:"
  #   private: no
  # - name: wifi_password
  #   prompt: "please enter the WiFi password for your new device:"
  #   private: yes
  - name: ssh_key
    prompt: "please enter the SSH Key for your new device:"
    private: yes
  - name: python_version
    prompt: "please enter the latest python version number in the form X.X.X:"
    private: no

  tasks:

    # Expand the filesystem
    - include: ../tasks/expand-filesystem.yml
      tags: setup

    # Set Internationalization Options
    - include: ../tasks/internationalization.yml
      tags: setup

    # Set WiFi Options
    # - include: ../tasks/wifi.yml
    #   tags: setup

    - name: Create SSH folder
      file: path=~/.ssh state=directory

    - name: Set up SSH Key from a template
      template: src=../templates/authorized_keys dest=~/.ssh/authorized_keys

    - name: run 'dpkg --configure -a'
      become: yes
      command: dpkg --configure -a

    # Run apt-get update and apt-get upgrade 
    - include: ../tasks/update.yml
      tags: update

    # Install base apt packages and libraries
    - include: ../tasks/base_packages.yml
      tags: setup

    # Download and install latest python version
    - include: ..tasks/install-latest-python.yml
      tags: setup

    # Install python libraries
    - include: ..tasks/install-python-modules.yml
      tags: setup

    # Configure virtualenvwrapper
    - include: ..tasks/virtualenvwrapper-configuration.yml
      tags:
        - virtualenvwrapper
        - virtualenvwrapper.configuration

    # Set the hostname
    - include: ../tasks/hostname.yml
      tags: setup

  handlers:

    - include: ../handlers/reboot.yml
      tags: system

    - include: ../handlers/tzdata.yml
      tags: system
